### ISSUE TITLE
CLICKING THE SAVE ICON BRINGS UP THE UPGRADE DIALOGUE 

### ISSUE THREAD

**Issue by Empressjanine** [h-unterp/dojobugs#16]
**Describe the bug**
Clicking the save icon next to the  question brings up the upgrade dialogue button.

1. Go to https://interview-dojo.web.app
2. Paste a resume 
3. Scroll down to click the "Submit" button below
4. Choose one question to save and click the "save" icon on the right of the question.
 

**Expected behavior**
User should be able to  save a question of choice.

Actual Behaviour
On clicking the save icon, the upgrade dialogue is seen below the home page

**Screencapture Video**
https://www.loom.com/share/2847ba7a97f641518c289141d2e84a7b

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Browser [chrome]
 - Version [113.0.5672.12]

**Additional context**

**Comment by h-unterp** [comment]
Was not able to confirm. 
If you delete account, then create a new account, you will see that you get 1 free save per 24 hour period.

**Comment by Empressjanine** [comment]
Thanks for the update.
