### ISSUE TITLE
User is unable to receive similar questions (Homepage)

### ISSUE THREAD

**Issue by Empressjanine** [h-unterp/dojobugs#19]
**Describe the bug**
The "similar question" icon opens up a blank page when clicked and brings up the upgrade dialogue screen when clicked a second time. 

1. Go to 'https://interview-dojo.web.app'
2. Click on 'copy and paste field box '
3. Type in "QA"
4. Click on the  submit button below
5. Choose a question and click on it to open a response field below.
6. Click on the "view similar questions" icon next to the "save" icon

**Expected behavior**
The user should be navigated to a page showing similar questions to the question chosen in the previous page .

Actual behaviour
The user is navigated to a blank page when "view similar questions" icon  is clicked once and when clicked a second time, The upgrade dialogue box opens up.

**Screencapture Video**
https://www.loom.com/share/9775d821204d460e9b48c3e295a1a448

**Desktop (please complete the following information):**
 
- OS: [Windows 10 Pro]
 - Browser [chrome]
 - Version [113.0.5672.12]

**Additional context**

**Comment by h-unterp** [comment]
Fixed in 5/25-19:00

**Comment by Empressjanine** [comment]
verified ,Bug fix
OS: [Windows 10 Pro]
Browser [chrome]
Version [113.0.5672.12]
