### ISSUE TITLE
User is unable to view saved question(Home page)

### ISSUE THREAD

**Issue by Empressjanine** [h-unterp/dojobugs#20]
**Describe the bug**
User is unable to view question saved on the "view saved question" icon.

**To Reproduce**
1.Go to 'https://interview-dojo.web.app'
2. Click on 'copy and paste field box '
3. Type in "QA"
4. Click on the  submit button below
5. Choose a question and click on the "save question" icon next to it 
6. Navigate to the "view saved questions"tab at the top right of the homepage.

**Expected behavior**
User should be able to view previously saved question,

Actual behaviour
User is navigated to a blank page .

**Screencapture Video**
https://www.loom.com/share/50399eb8102b46e79f5427721a8d365b

**Desktop (please complete the following information):**

 -OS: [Windows 10 Pro]
 - Browser [chrome]
 - Version [113.0.5672.12]

**Additional context**

**Comment by h-unterp** [comment]
Fixed in 5/25-19:00

**Comment by Empressjanine** [comment]
Verified bug fix
-OS: [Windows 10 Pro]
-Browser [chrome]
-Version [113.0.5672.12]
