### ISSUE TITLE
Upgraded user is unable to get a response after uploading  a resume

### ISSUE THREAD

**Issue by Empressjanine** [h-unterp/dojobugs#21]
**Describe the bug**
The Upgrade dialogue button comes up after the upgraded user logs out and logs in again

**To Reproduce**
1. Go to : https://interview-dojo.web.app
2.Click the upload resume button on the top of the homepage
3.Click the upgrade button shown in the dialogue box.
4. Fill in the field with the "Test data" card credentials in the payment field.
5. After a successful payment message is received.
6. Sign out of the web app and sign back in
7. click on the upload resume icon
**Expected behavior**
The paid user should be able to get a response after uploading a resume
**Screencapture Video**
https://www.loom.com/share/d4e5a1db0d2645ed8362ceac78e96e5b

![clicking back arrow](https://github.com/h-unterp/dojobugs/assets/93427231/da7b61a1-98d9-41ed-acc0-0226f8b600a6)

**Desktop (please complete the following information):**
 - OS: Windows 10 PRO
 - Browser [ chrome]
 - Version [ 113.0.5672.127]

**Additional context**
On clicking the back button to navigate to the previous page,a message box saying the user verified email link is expired is received

**Comment by h-unterp** [comment]
fixed
