### ISSUE TITLE
Doesn't advance to next screen

### ISSUE THREAD

**Issue by ghost** [h-unterp/dojobugs#3]
Using both mobile Bing and Chrome browsers
Login using Google account
Pasted only my Professional Experience
Clicked on the Page with Arrow button
Page does not advance
I repeat, page does not advance
Over

**Comment by h-unterp** [comment]
"Clicked on the Page with Arrow button"  

The only arrow button is the back button, see attached picture, so if that is button you pressed...then it would make sense that nothing advanced. 

Can you supply a screen recording for all bug reports moving forward? It would save a lot of time in guessing what is meant in these reports.

![Screenshot 2023-05-22 at 5 52 11 PM](https://github.com/h-unterp/dojobugs/assets/772917/8e2e77b5-cc5c-4c8f-926d-da37d491c853)
