### ISSUE TITLE
USER UNABLE TO NAVIGATE TO THE SUBMIT BUTTON(Home Page)

### ISSUE THREAD

**Issue by Empressjanine** [h-unterp/dojobugs#4]
DESCRIPTION
User is unable to navigate to the submit button

Steps to reproduce:
1. Go to https://interview-dojo.web.app
2. Click on the field box  with "copy and paste your resume"
3. paste a  sample resume
4. Navigate down  the bottom using the down arrow key on a desktop computer

**Expected behavior**
user should be able to navigate to the bottom of the page and a submit button should be seen.

**Screencapture Video**
https://www.loom.com/share/ba5d0b8ff7984f6784911c8e2f0b7051

**Desktop (please complete the following information):**
 - OS: Windows 10 PRO
 - Browser [ chrome ]
 - Version [Version 113.0.5672.127 ]
-System Name   DESKTOP-KQNQ5GQ

**Additional context**
As the user is unable to navigate to the submit button ,it is  a blocker that prevents the user from further testing .

**Comment by h-unterp** [comment]
Fixed @Empressjanine  Down button won't work, but mouse will work, there is now a scroll bar at right side.

**Comment by Empressjanine** [comment]
Thanks @h-unterp will check it and start testing
